### ISSUE TITLE
Use Lua commenting style

### ISSUE THREAD

**Issue by xDShot** [buu342/GMod-BuuBaseRedone#1]
C++ style comments mess up readability on github and many other editors. Hard to tell if parts are really commented...

**Comment by buu342** [comment]
Aww man, that's gonna be so much work to port over :pensive:

**Comment by xDShot** [comment]
Thanks! This greatly improves readability, and I don't have to download whole repo so I can read it in browser! 👍

**Comment by KM-CM** [comment]
I think the other way. You just have to use
// single line comments
// for block comments
and it is very clear what is commented and what isn't.
Plus the C styled comments were ported for a reason, they look cooler.
But whatever your heart desires, to be honest. No idea why I wrote this.
